name: PR Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test-workflow:
    name: B&T
    runs-on: [macos-13]
    steps:
    - uses: actions/checkout@v3.5.3
    - name: Run build_and_test.sh
      run: scripts/build_and_test.sh
