name: PR Workflow

on:
  push:
    branches: [ main ]

jobs:
  build-and-test-workflow:
    name: B&T
    runs-on: [self-hosted, macOS]
    steps:
    - uses: actions/checkout@v3.5.3
    - name: Swift Package Smoke Test
      run: swift run -c release SmokeTest
